name: CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Publish
        run: |
          echo "Configure np package to publish package"
